#!/bin/sh

mount -o remount,rw /

###########################
### New device UWS-THPL ###
###########################
device="HB-UW-Sen-THPL"

### Copy new devices Files ###
cp -a firmware/rftypes/* /firmware/rftypes/

### Copy new images ###
cp -ar www/config/img/devices /www/config/img/

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert=""
devdescrInsert="$devdescrInsert HB-UW-Sen-THPL-I {{50 \/config\/img\/devices\/50\/hb-uw-sen-thpl-i_thumb.png} {250 \/config\/img\/devices\/250\/hb-uw-sen-thpl-i.png}} "
devdescrInsert="$devdescrInsert HB-UW-Sen-THPL-O {{50 \/config\/img\/devices\/50\/hb-uw-sen-thpl-o_thumb.png} {250 \/config\/img\/devices\/250\/hb-uw-sen-thpl-o.png}} "

if [ -z "`cat $devdescrFile | grep \"$device\"`" ]; then
	cp -a $devdescrFile $devdescrFile.save
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

### Edit webui.js ###
webuiFile="/www/webui/webui.js"
webuiSearch="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"

webuiInsert="\n"
webuiInsert="$webuiInsert DEV_HIGHLIGHT['HB-UW-Sen-THPL-I'] = new Object();\n"
webuiInsert="$webuiInsert DEV_LIST.push('HB-UW-Sen-THPL-I');\n"
webuiInsert="$webuiInsert DEV_DESCRIPTION['HB-UW-Sen-THPL-I']='Universal Funk- Temperatur-\/ Feuchte-\/ Luftdruck-\/ Helligkeitssensor (Innen)';\n"
webuiInsert="$webuiInsert DEV_PATHS['HB-UW-Sen-THPL-I'] = new Object();\n"
webuiInsert="$webuiInsert DEV_PATHS['HB-UW-Sen-THPL-I']['50'] = '\/config\/img\/devices\/50\/hb-uw-sen-thpl-i_thumb.png';\n"
webuiInsert="$webuiInsert DEV_PATHS['HB-UW-Sen-THPL-I']['250'] = '\/config\/img\/devices\/250\/hb-uw-sen-thpl-i.png';\n"

webuiInsert="$webuiInsert DEV_HIGHLIGHT['HB-UW-Sen-THPL-O'] = new Object();\n"
webuiInsert="$webuiInsert DEV_LIST.push('HB-UW-Sen-THPL-O');\n"
webuiInsert="$webuiInsert DEV_DESCRIPTION['HB-UW-Sen-THPL-O']='Universal Funk- Temperatur-\/ Feuchte-\/ Luftdruck-\/ Helligkeitssensor (Außen)';\n"
webuiInsert="$webuiInsert DEV_PATHS['HB-UW-Sen-THPL-O'] = new Object();\n"
webuiInsert="$webuiInsert DEV_PATHS['HB-UW-Sen-THPL-O']['50'] = '\/config\/img\/devices\/50\/hb-uw-sen-thpl-o_thumb.png';\n"
webuiInsert="$webuiInsert DEV_PATHS['HB-UW-Sen-THPL-O']['250'] = '\/config\/img\/devices\/250\/hb-uw-sen-thpl-o.png';\n"

if [ -z "`cat $webuiFile | grep \"$device\"`" ]; then
	sed -i "s/\($webuiSearch\)/\1$webuiInsert/g" $webuiFile
fi

sync

mount -o remount,ro /